export { default as HomePage } from './home';
export { default as ButtonPage } from './button';
export { default as IconPage } from './icon';
export { default as CellPage } from './cell';
export { default as NavBarPage } from './nav-bar';
export { default as ToastPage } from './toast';
export { default as TagPage } from './tag';
export { default as TabBarPage } from './tab-bar';
export { default as StepPage } from './step';
